### ISSUE TITLE
Add Posh Link in Repo "About"

### ISSUE THREAD

**Issue by tajmone** [pxml-lang/pxml-lang.github.io#4]
Christian, I hope you don't me having taken the liberty of creating a «posh URL» pointing to [pxml-lang.github.io] via [Git.io]:

- [git.io/pxml-lang]

I originally wanted to create the [git.io/pxml] URL, which can't be done via the [Git.io] website (to use a keyword other than the repository name you need to do it via a cURL script, hence my intrusion), but unfortunately it's already taken up :cry: by someone else, so I just went for pxml-lang.

- [x] Edit **About** » **Website** field, add new posh URL: [git.io/pxml-lang]

See also my tips from pml-lang/converter#32 on how to improve visibility of the repository on GitHub.

[pxml-lang.github.io]: https://pxml-lang.github.io/
[Git.io]: https://git.io/
[git.io/pxml-lang]: https://git.io/pxml-lang
[git.io/pxml]: https://git.io/pxml

**Comment by pxml-lang** [comment]
Thank you, Tristano.
